apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: menelik7/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: menelik7/client
      context: client
      sync:
        manual:
          - src: "**/*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: menelik7/tickets
      context: tickets
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  # local:
  #   push: false
#   googleCloudBuild:
#     projectId: ticketing-dev-395718
manifests:
  rawYaml:
    - ./infra/k8s/*
